import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import axios from 'axios'
import { useSelector } from 'react-redux'
import config from '../config'
import { Card, Comment, FormField } from '../components'

const PostDetails = () => {
    const { id } = useParams();
    const [comment, setComment] =  useState('');
    const [allComments, setAllComments] = useState([]);
    const [postData, setPostData] = useState(null);
    const [update, setUpdate] = useState(false);
    const { token } = useSelector(data => data);
    useEffect(() => {
        fetchPosts(id);
    }, [update]);

    const fetchPosts = async (id) => {
        try {
            let res = await axios.get(`${config.API_URL}/api/v1/post/getone/${id}`, {
                headers: {
                    'authorization' : `Bearer ${token}`
                }
            });
            if(res.data.success){
                setPostData(res.data.data);
                setAllComments([...res.data.data.comments.reverse()]);
            }
        } catch (err) {
            console.log(err);
        }
    }

    const handleChange = (e) => {
        setComment(e.target.value);
    }

    const addComment = async () => {
        if(comment) {
            try {
                let res = await axios.post(`${config.API_URL}/api/v1/post/comment`, {
                    comment,
                    id
                },{
                    headers: {
                        'authorization' : `Bearer ${token}`
                    }
                })

                console.log(res);
                setComment("");
                setUpdate(!update);
            } catch (err) {
                console.log(err);
            }
        }
    }
  return (
    <section className="max-w-7xl mx-auto mt-20">
        <div>
            <h1 className="font-extrabold text-[#222328] text-[32px]" >The Community Showcase</h1>
            <p className="mt-2 text-[#666e75] text-[16px] max-w-[600px]">Browse through a collection of imaginative and visually stunning images generated by VisualizeAI</p>
        </div>

        <div className="grid grid-cols-2 max-lg:grid-cols-1 gap-10">
            <div className="">
                { postData && <Card { ...postData } /> }
            </div>
            <div className="border-2 rounded-lg px-5 py-3">
                <h1 className="text-center text-xl" >Comments</h1>
                <div className="flex items-center">
                    <div className="w-[80%]">
                        <FormField 
                            handleChange={ handleChange  }
                            type="text"
                            name="text"
                            placeholder="Add a comment..."
                            value={ comment }
                        />
                    </div>
                    <div className="w-[20%] flex items-center mt-2">
                        <button type="button"
                            className="bg-green-600 text-white w-full py-3 ml-2 rounded-md text-sm"
                            onClick={ addComment }
                        >Post</button>
                    </div>
                </div>

                <div className="mt-4">
                    {
                        allComments.map((ele) => {
                            return <Comment key={ele.comment+ele.name} {...ele} />
                        })
                    }
                </div>
            </div>
        </div>
    </section>
  )
}

export default PostDetails;
